JUnit: test_warn_plugin_double_fail.myfirstfai1ure: Is our warnings plugin able to trace this random failure msg?
JUnit: test_warn_plugin_no_double_fail.mysecondfai1ure: Second failure
